# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joininvitation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Sent'), (2, 'Accepted'), (3, 'Joined Independently')]),
        ),
    ]
